## View

**Laravel**

{{}} se usa para mostrar datos pasados al fichero blade desde la ruta (como por ejemplo los valores pasados 
desde Eloquent)

Para pasar datos desde Eloquent a los view de blade se devuelve en la funcion llamada en la ruta 
usando el helper view('folder.viewfile', ['varname' => 'Value']). Esto enviara el valor del varname 
al fichero viewfile contenido en la carpeta folder.

## Blade

**Laravel**

@extends: 
@section: 

## Eloquent

**Laravel**

* Model::find($valor): busca en la BD la fila cuya primary key es igual al valor de $valor para el modelo de datos Model.

## 7. Dynamic Route Parameter

**Laravel**

Dynamic Route consiste en insertar un elemento que no es fijo en la ruta, 
como podria ser por ejemplo el valor de un parametro. En este proyecto, se 
usara para editar las notas ya que cada nota tiene un id asignado, la ruta 
editar debera contener el id de la nota para poder modificarla.

Para indicar que el parametro tiene que ser requerido en la ruta se usa {}.
Se puede observar en el fichero web.php que se ha insertado un parametro requerido 
en la ruta de edicion de la nota.

Al pasar el parametro en la ruta usando {} (que es lo que se llama *Dynamic Route parameter*), cuando se llama al metodo en el controlador
se puede recoger ese valor como parametro del metodo (vease editar ToDo en el proyecto)

**HTML tags**

* <div>: Defines a division or a section in HTML. Easily styled by class or id.
* <div class="" >: attribute wich specifies one or more class names for an HTML element.
* <a>: defines a hyperlink, used to link from one page to another
* <a href="">: defines the route of the hyperlink 
* <p>: defines a paragraph

**TailwindCSS**

* class="flex": creates a flexbox inside the tags to control how items grow and shrink
* class="justify-center": align elements to the center
* class="mx-5": equals to margin 1.25 rem in x axis
* class="py-1": padding 0.25 rem in y axis
* class="px-1": padding 0.25 rem in y axis
* class="p-1": padding 0.25 rem in x and y axis
* class="text-2xl": font-size of 1.5 rem
* class="bg-blue-300": element background color (blue-300)
* class="cursor-pointer": cursor style while hover. Change to pointing hand
* class="rounded": border radius of an element with 0.25 rem
* class="text-white": text color of an element (white)

## 8. Route model binding

**Laravel**

* Implicit binding: ruta dinamica '/todos/{id}/edit' se pasa el valor del id. en el controlador
se puede recoger ese valor como function edit($id). Laravel puede ir mas alla, si se especifica el 
modelo en el metodo, Laravel injectara el objeto correspondiente a ese id si se escribe asi:
function edit(Todo $id) [nota, el nombre del parametro debe ser igual al que hay en la ruta]. 
Ahora laravel ha recogido de la BD la fila dentro de la tabla Todo cuyo id se corresponde con el 
valor pasado. Para no confundir, se va a cambiar la ruta a todo. De esta forma, nos ahorramos la linea de
Todo::find

* Key personalizadas: con Implicit binding, si no se especifica nada, siempre se pasara en la ruta el id del
objeto. Si se quiere pasar otro dato en la ruta se puede hacer asi {todo:title} (si se quiere pasar el titulo)

* Key personalizada por defecto: en caso de que se quiera cambiar el valor del implicit binding por defecto, se puede 
hacer desde la clase del model Todo, haciendo que el metodo getRouteKeyName() devuelva el atributo que queramos (por ejemplo title)
(el metodo lo tienes que crear tu mismo porque no te viene en la plantilla del modelo)

[CREO QUE NO TERMINO DE ENTENDERLO]

**HTML**
<input value="">: especifica el valor contenido dentro del input

## 9. Named routes

**Laravel**

*@csrf: sirve como metodo de proteccion ante un ataque cross-site request forgery. Protege ante que un usuario que no 
se corresponde con el autentificado haga acciones en la web.

*@method(patch): los form de HTML solo tienen como action GET y POST. Si se quiere usar otro metodo, se debe usar este codigo

*Route::patch: al igual que PUT se usan para modificar valores en el servidor. A diferencia de put, patch se usa para cambiar 
un solo valor del modelo de datos del servidor (si hay que cambiar mas datos de la fila se deberia usar PUT, aunque tambien se 
puede usar PUT para hacer cambios en un solo atributo).

*Route::get('/nombre/cosa')->name('alias'): a una ruta se le puede poner un alias para identificarla luego en el codigo.
Para hacer referencia a la ruta en blade se usa {{ route('alias', $modelo->valor) }}. Esto llamara a la ruta alias y pasara 
el parametro indicado a la ruta (por ejemplo, si alias es '/todo/{valor}/cosa').

*redirect(route('nombreruta')): redirecciona a la ruta indicada.

[PARA CUANDO VUELVAS, REDACTA LO QUE HAS HECHO EN EL METODO UPDATE DEL TODO CONTROLLER] [NO TERMINO DE ENTENDERLO]
